### ISSUE TITLE
Computation of local similarities for two gallery images

### ISSUE THREAD

**Issue by xuxu116** [dapengchen123/crf_affinity#2]
Thanks for releasing your code and it runs smoothly!

There is some details in the implementation about the local similarities that I don't fully understand. As mentioned in your paper the local similarities are computed by the LS module (FC+BN ...) but I found in the code that local similarities between all pairs of gallery images are computed by naive Feature distance as:
https://github.com/dapengchen123/crf_affinity/blob/master/reid/train/trainers.py#L573-L588

And I don't get the meaning of 'gamma=3' term in the above code. Could you kindly give more explanations? Thx

**Comment by dapengchen123** [comment]
@xuxu116  Oh, Yes, you are right. The local similarity here is not  computed as it is reported in the paper. The \gamma here is a hyper-parameter to project the distance ranged within (-1,1 ) to similarity  ranged in (0,1).  There is no specific meanings for gamma.

**Comment by insikk** [comment]
@dapengchen123 Can you tell us the reason behind your choice of using pairwise_dist for (gallery,gallery) pair, but using local similarity module for (probe,gallery) ? Is it better than using LS for all pairs?

**Comment by dapengchen123** [comment]
@insikk   In our following study, we found that the local similarities, which have additional parameters over the feature distances, are easily becoming 1 and 0 for positive pairs and negative pairs, respectively. It may not reasonably reflect the affinity between the training samples. :)

**Comment by xuxu116** [comment]
@dapengchen123 Thanks for your explanation!
